<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-MB50M7DV" failures="2" tests="4" name="Practice12.TwitterTestNG" time="32.320" errors="0" timestamp="2022-09-17T19:47:32 IST" skipped="0">
  <testcase classname="Practice12.TwitterTestNG" name="A_verifyTwitterCompromisedAccount" time="4.865">
    <failure message="The following asserts failed:
	expected [https://help.twitter.com/en/safety-and-security/twitter-account-compromise] but found [https://help.twitter.com/en/safety-and-security/twitter-account-compromised]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [https://help.twitter.com/en/safety-and-security/twitter-account-compromise] but found [https://help.twitter.com/en/safety-and-security/twitter-account-compromised]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at Practice12.TwitterTestNG.A_verifyTwitterCompromisedAccount(TwitterTestNG.java:81)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- A_verifyTwitterCompromisedAccount -->
  <system-out/>
  <testcase classname="Practice12.TwitterTestNG" name="A_verifyTwitterCompromisedAccount" time="15.380">
    <failure message="The following asserts failed:
	expected [https://help.twitter.com/en/safety-and-security/twitter-account-compromise] but found [https://help.twitter.com/en/safety-and-security/twitter-account-compromised]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [https://help.twitter.com/en/safety-and-security/twitter-account-compromise] but found [https://help.twitter.com/en/safety-and-security/twitter-account-compromised]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at Practice12.TwitterTestNG.A_verifyTwitterCompromisedAccount(TwitterTestNG.java:81)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- A_verifyTwitterCompromisedAccount -->
  <system-out/>
  <testcase classname="Practice12.TwitterTestNG" name="B_verifyTwitterAccountSecurity" time="7.752"/>
  <system-out/>
  <testcase classname="Practice12.TwitterTestNG" name="B_verifyTwitterAccountSecurity" time="4.323"/>
  <system-out/>
</testsuite> <!-- Practice12.TwitterTestNG -->
